# thresholds:
#   cpu:
#     warning: 80
#     critical: 90

#   memory:
#     warning: 80
#     critical: 90

#   disk:
#     warning: 85
#     critical: 95

thresholds:
  cpu:
    warning: 1
    critical: 3

  memory:
    warning: 1
    critical: 3

  disk:
    warning: 1
    critical: 3